#version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-cabinetavocat}
      MYSQL_USER: ${DB_USER:-avocat}
      MYSQL_PASSWORD: ${DB_PASSWORD:-avocatpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 30


  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-cabinetavocat}
      DB_USER: ${DB_USER:-avocat}
      DB_PASSWORD: ${DB_PASSWORD:-avocatpass}
      SECRET_KEY: ${SECRET_KEY:-dev-insecure-key}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${WEB_HOST_PORT:-8000}:8000"
    volumes:
      - .:/app

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    env_file:
      - .env
    environment:
      # Vite will read this and your app can use import.meta.env.VITE_API_URL
      VITE_API_URL: ${VITE_API_URL:-http://web:8000}
      # Needed for hot-reload behind Docker
      HOST: 0.0.0.0
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "${FRONTEND_HOST_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    depends_on:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USER:-avocat}
      PMA_PASSWORD: ${DB_PASSWORD:-avocatpass}
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_HOST_PORT:-8080}:80"

volumes:
  db_data:
  frontend_node_modules:
