# Generated by Django 5.2.4 on 2025-07-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affairejudiciaire',
            fields=[
                ('idaffaire', models.CharField(db_collation='latin1_swedish_ci', db_column='idAffaire', max_length=50, primary_key=True, serialize=False)),
                ('dateouverture', models.DateField(db_column='dateOuverture')),
                ('datecloture', models.DateField(blank=True, db_column='dateCloture', null=True)),
            ],
            options={
                'db_table': 'affairejudiciaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Affairetribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesaisine', models.DateField(db_column='dateSaisine')),
                ('datejugement', models.DateField(blank=True, db_column='dateJugement', null=True)),
            ],
            options={
                'db_table': 'affairetribunal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('idaudience', models.CharField(db_collation='latin1_swedish_ci', db_column='idAudience', max_length=50, primary_key=True, serialize=False)),
                ('dateaudience', models.DateField(db_column='dateAudience')),
                ('remarques', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
            ],
            options={
                'db_table': 'audience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('idavocat', models.CharField(db_collation='latin1_swedish_ci', db_column='idAvocat', max_length=50, primary_key=True, serialize=False)),
                ('nomavocat', models.CharField(db_collation='latin1_swedish_ci', db_column='nomAvocat', max_length=255)),
                ('specialisation', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'avocat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(db_column='idClient', primary_key=True, serialize=False)),
                ('nomclient', models.CharField(db_collation='latin1_swedish_ci', db_column='nomClient', max_length=255)),
                ('adresseclient', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='adresseClient', null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapejudiciaire',
            fields=[
                ('idetape', models.CharField(db_collation='latin1_swedish_ci', db_column='idEtape', max_length=50, primary_key=True, serialize=False)),
                ('datedebut', models.DateField(db_column='dateDebut')),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
            ],
            options={
                'db_table': 'etapejudiciaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('idexpert', models.CharField(db_collation='latin1_swedish_ci', db_column='idExpert', max_length=50, primary_key=True, serialize=False)),
                ('nomexpert', models.CharField(db_collation='latin1_swedish_ci', db_column='nomExpert', max_length=255)),
                ('specialisationexpert', models.CharField(db_collation='latin1_swedish_ci', db_column='specialisationExpert', max_length=255)),
                ('telephoneexpert', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='telephoneExpert', max_length=20, null=True)),
            ],
            options={
                'db_table': 'expert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idfacture', models.CharField(db_collation='latin1_swedish_ci', db_column='idFacture', max_length=50, primary_key=True, serialize=False)),
                ('montantfacture', models.FloatField(db_column='montantFacture')),
                ('datefacture', models.DateField(db_column='dateFacture')),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huissier',
            fields=[
                ('idhuissier', models.CharField(db_collation='latin1_swedish_ci', db_column='idHuissier', max_length=50, primary_key=True, serialize=False)),
                ('nomhuissier', models.CharField(db_collation='latin1_swedish_ci', db_column='nomHuissier', max_length=255)),
                ('adressehuissier', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='adresseHuissier', null=True)),
                ('telephonehuissier', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='telephoneHuissier', max_length=20, null=True)),
            ],
            options={
                'db_table': 'huissier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paiementhonoraires',
            fields=[
                ('idpaiement', models.CharField(db_collation='latin1_swedish_ci', db_column='idPaiement', max_length=50, primary_key=True, serialize=False)),
                ('pourcentagepaiement', models.FloatField(db_column='pourcentagePaiement')),
                ('montantpaiement', models.FloatField(db_column='montantPaiement')),
                ('datepaiement', models.DateField(db_column='datePaiement')),
            ],
            options={
                'db_table': 'paiementhonoraires',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participationexpertetape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateintervention', models.DateField(db_column='dateIntervention')),
                ('typeintervention', models.CharField(db_collation='latin1_swedish_ci', db_column='typeIntervention', max_length=100)),
            ],
            options={
                'db_table': 'participationexpertetape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participationhuissieretape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateintervention', models.DateField(db_column='dateIntervention')),
                ('typeintervention', models.CharField(db_collation='latin1_swedish_ci', db_column='typeIntervention', max_length=100)),
            ],
            options={
                'db_table': 'participationhuissieretape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participationtemoinetape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateintervention', models.DateField(db_column='dateIntervention')),
                ('typeintervention', models.CharField(db_collation='latin1_swedish_ci', db_column='typeIntervention', max_length=100)),
            ],
            options={
                'db_table': 'participationtemoinetape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatutAffaire',
            fields=[
                ('idstatutaffaire', models.AutoField(db_column='idStatutAffaire', primary_key=True, serialize=False)),
                ('libellestatutaffaire', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleStatutAffaire', max_length=100)),
                ('datedebut', models.DateField(db_column='dateDebut')),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
            ],
            options={
                'db_table': 'statut_affaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatutAffairetribunal',
            fields=[
                ('idstatutaffairetribunal', models.AutoField(db_column='idStatutAffaireTribunal', primary_key=True, serialize=False)),
                ('libellestatutaffairetribunal', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleStatutAffaireTribunal', max_length=100)),
                ('datedebut', models.DateField(db_column='dateDebut')),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
            ],
            options={
                'db_table': 'statut_affairetribunal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatutAudience',
            fields=[
                ('idstatutaudience', models.AutoField(db_column='idStatutAudience', primary_key=True, serialize=False)),
                ('libellestatutaudience', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleStatutAudience', max_length=100)),
                ('datedebut', models.DateField(db_column='dateDebut')),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
            ],
            options={
                'db_table': 'statut_audience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatutEtape',
            fields=[
                ('idstatutetape', models.AutoField(db_column='idStatutEtape', primary_key=True, serialize=False)),
                ('libellestatutetape', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleStatutEtape', max_length=100)),
                ('datedebut', models.DateField(db_column='dateDebut')),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
            ],
            options={
                'db_table': 'statut_etape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatutFacture',
            fields=[
                ('idstatutfacture', models.AutoField(db_column='idStatutFacture', primary_key=True, serialize=False)),
                ('libellestatutfacture', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleStatutFacture', max_length=100)),
                ('datedebut', models.DateField(db_column='dateDebut')),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
            ],
            options={
                'db_table': 'statut_facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('idtemoin', models.CharField(db_collation='latin1_swedish_ci', db_column='idTemoin', max_length=50, primary_key=True, serialize=False)),
                ('nomtemoin', models.CharField(db_collation='latin1_swedish_ci', db_column='nomTemoin', max_length=255)),
                ('adressetemoin', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='adresseTemoin', null=True)),
                ('roletemoin', models.CharField(db_collation='latin1_swedish_ci', db_column='roleTemoin', max_length=100)),
                ('telephonetemoin', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='telephoneTemoin', max_length=20, null=True)),
            ],
            options={
                'db_table': 'temoin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('idtribunal', models.CharField(db_collation='latin1_swedish_ci', db_column='idTribunal', max_length=50, primary_key=True, serialize=False)),
                ('nomtribunal', models.CharField(db_collation='latin1_swedish_ci', db_column='nomTribunal', max_length=255)),
                ('adressetribunal', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='adresseTribunal', null=True)),
                ('villetribunal', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='villeTribunal', max_length=100, null=True)),
                ('telephonetribunal', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='telephoneTribunal', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tribunal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAffaire',
            fields=[
                ('idtypeaffaire', models.AutoField(db_column='idTypeAffaire', primary_key=True, serialize=False)),
                ('libelletypeaffaire', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleTypeAffaire', max_length=100)),
            ],
            options={
                'db_table': 'type_affaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('idtypeclient', models.AutoField(db_column='idTypeClient', primary_key=True, serialize=False)),
                ('libelletypeclient', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleTypeClient', max_length=100)),
            ],
            options={
                'db_table': 'type_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('idtypecontrat', models.AutoField(db_column='idTypeContrat', primary_key=True, serialize=False)),
                ('libelletypecontrat', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleTypeContrat', max_length=100)),
            ],
            options={
                'db_table': 'type_contrat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEtape',
            fields=[
                ('idtypeetape', models.AutoField(db_column='idTypeEtape', primary_key=True, serialize=False)),
                ('libelletypeetape', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleTypeEtape', max_length=100)),
            ],
            options={
                'db_table': 'type_etape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('idtypeintervention', models.AutoField(db_column='idTypeIntervention', primary_key=True, serialize=False)),
                ('libelletypeintervention', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleTypeIntervention', max_length=100)),
            ],
            options={
                'db_table': 'type_intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeTribunal',
            fields=[
                ('idtypetribunal', models.AutoField(db_column='idTypeTribunal', primary_key=True, serialize=False)),
                ('libelletypetribunal', models.CharField(db_collation='latin1_swedish_ci', db_column='libelleTypeTribunal', max_length=100)),
            ],
            options={
                'db_table': 'type_tribunal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('idcontrat', models.CharField(db_collation='latin1_swedish_ci', db_column='idContrat', max_length=50, primary_key=True, serialize=False)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('idclient', models.ForeignKey(blank=True, db_column='idClient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.client')),
                ('idtypecontrat', models.ForeignKey(blank=True, db_column='idTypeContrat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.typecontrat')),
            ],
            options={
                'db_table': 'contrat',
                'managed': True,
            },
        ),
    ]
