# Generated by Django 5.2.4 on 2025-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionClient',
            fields=[
                ('idfonction', models.AutoField(primary_key=True, serialize=False)),
                ('libellefonction', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'fonction_client',
            },
        ),
        migrations.CreateModel(
            name='Opposant',
            fields=[
                ('idopposant', models.AutoField(db_column='idOpposant', primary_key=True, serialize=False)),
                ('nomopposant', models.CharField(db_column='nomOpposant', max_length=255)),
                ('adresse1', models.CharField(blank=True, db_column='adresse1', max_length=255, null=True)),
                ('adresse2', models.CharField(blank=True, db_column='adresse2', max_length=255, null=True)),
                ('numtel1', models.CharField(blank=True, db_column='numTel1', max_length=20, null=True)),
                ('numtel2', models.CharField(blank=True, db_column='numTel2', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'opposant',
            },
        ),
        migrations.AlterModelOptions(
            name='affairejudiciaire',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
    ]
