# Generated by Django 5.2.4 on 2025-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audience',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='categorieaffaire',
            old_name='libelle',
            new_name='libelle_ar',
        ),
        migrations.RenameField(
            model_name='demandesfichier',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='fonctionclient',
            old_name='libellefonction',
            new_name='libellefonction_ar',
        ),
        migrations.RenameField(
            model_name='juge',
            old_name='nomjuge',
            new_name='nomjuge_ar',
        ),
        migrations.RenameField(
            model_name='juge',
            old_name='prenomjuge',
            new_name='nomjuge_fr',
        ),
        migrations.RenameField(
            model_name='juge',
            old_name='specialisation',
            new_name='specialisation_ar',
        ),
        migrations.RenameField(
            model_name='soustypeaffaire',
            old_name='libelle',
            new_name='libelle_ar',
        ),
        migrations.RenameField(
            model_name='tribunal',
            old_name='adressetribunal',
            new_name='adressetribunal_ar',
        ),
        migrations.RenameField(
            model_name='tribunal',
            old_name='nomtribunal',
            new_name='nomtribunal_ar',
        ),
        migrations.RenameField(
            model_name='tribunal',
            old_name='villetribunal',
            new_name='villetribunal_ar',
        ),
        migrations.RenameField(
            model_name='typeaffaireprincipale',
            old_name='libelle',
            new_name='libelle_ar',
        ),
        migrations.RenameField(
            model_name='typetribunal',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='typetribunal',
            old_name='libelletypetribunal',
            new_name='libelletypetribunal_ar',
        ),
        migrations.RemoveField(
            model_name='avocat',
            name='nomavocat',
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nomclient',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='nomexpert',
        ),
        migrations.RemoveField(
            model_name='huissier',
            name='adressehuissier',
        ),
        migrations.RemoveField(
            model_name='huissier',
            name='nomhuissier',
        ),
        migrations.RemoveField(
            model_name='opposant',
            name='adresse1',
        ),
        migrations.RemoveField(
            model_name='opposant',
            name='adresse2',
        ),
        migrations.RemoveField(
            model_name='opposant',
            name='nomopposant',
        ),
        migrations.RemoveField(
            model_name='temoin',
            name='adressetemoin',
        ),
        migrations.RemoveField(
            model_name='temoin',
            name='nomtemoin',
        ),
        migrations.RemoveField(
            model_name='typeaffaire',
            name='libelletypeaffaire',
        ),
        migrations.RemoveField(
            model_name='typeclient',
            name='libelletypeclient',
        ),
        migrations.RemoveField(
            model_name='typecontrat',
            name='libelletypecontrat',
        ),
        migrations.RemoveField(
            model_name='typeintervention',
            name='libelletypeintervention',
        ),
        migrations.AddField(
            model_name='audience',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='nomavocat_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomAvocat_ar', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avocat',
            name='nomavocat_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomAvocat_fr', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorieaffaire',
            name='libelle_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='adresse1_ar',
            field=models.CharField(blank=True, db_column='adresse1_ar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse1_fr',
            field=models.CharField(blank=True, db_column='adresse1_fr', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse2_ar',
            field=models.CharField(blank=True, db_column='adresse2_ar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse2_fr',
            field=models.CharField(blank=True, db_column='adresse2_fr', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nomclient_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomClient_ar', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='nomclient_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomClient_fr', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandesfichier',
            name='description_fr',
            field=models.TextField(default='', help_text='Description détaillée de la demande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='nomexpert_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomExpert_ar', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='nomexpert_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomExpert_fr', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fonctionclient',
            name='libellefonction_fr',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huissier',
            name='adressehuissier_ar',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='adresseHuissier_ar', null=True),
        ),
        migrations.AddField(
            model_name='huissier',
            name='adressehuissier_fr',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='adresseHuissier_fr', null=True),
        ),
        migrations.AddField(
            model_name='huissier',
            name='nomhuissier_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomHuissier_ar', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huissier',
            name='nomhuissier_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomHuissier_fr', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juge',
            name='prenomjuge_ar',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juge',
            name='prenomjuge_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juge',
            name='specialisation_fr',
            field=models.CharField(blank=True, help_text='Spécialisation du juge', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opposant',
            name='adresse1_ar',
            field=models.CharField(blank=True, db_column='adresse1_ar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opposant',
            name='adresse1_fr',
            field=models.CharField(blank=True, db_column='adresse1_fr', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opposant',
            name='adresse2_ar',
            field=models.CharField(blank=True, db_column='adresse2_ar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opposant',
            name='adresse2_fr',
            field=models.CharField(blank=True, db_column='adresse2_fr', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opposant',
            name='nomopposant_ar',
            field=models.CharField(db_column='nomOpposant_ar', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opposant',
            name='nomopposant_fr',
            field=models.CharField(db_column='nomOpposant_fr', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soustypeaffaire',
            name='libelle_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temoin',
            name='adressetemoin_ar',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='adresseTemoin_ar', null=True),
        ),
        migrations.AddField(
            model_name='temoin',
            name='adressetemoin_fr',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='adresseTemoin_fr', null=True),
        ),
        migrations.AddField(
            model_name='temoin',
            name='nomtemoin_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomTemoin_ar', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temoin',
            name='nomtemoin_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='nomTemoin_fr', default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribunal',
            name='adressetribunal_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='nomtribunal_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribunal',
            name='villetribunal_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeaffaire',
            name='libelletypeaffaire_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeAffaire_ar', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeaffaire',
            name='libelletypeaffaire_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeAffaire_fr', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeaffaireprincipale',
            name='libelle_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeclient',
            name='libelletypeclient_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeClient_ar', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeclient',
            name='libelletypeclient_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeClient_fr', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typecontrat',
            name='libelletypecontrat_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeContrat_ar', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typecontrat',
            name='libelletypecontrat_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeContrat_fr', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeintervention',
            name='libelletypeintervention_ar',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeIntervention_ar', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeintervention',
            name='libelletypeintervention_fr',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_column='libelleTypeIntervention_fr', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typetribunal',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typetribunal',
            name='libelletypetribunal_fr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='numtel1',
            field=models.CharField(blank=True, db_column='numTel1_fr', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='numtel2',
            field=models.CharField(blank=True, db_column='numTel2_ar', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('ar', 'العربية')], default='ar', help_text="Langue préférée de l'interface utilisateur", max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='opposant',
            name='numtel1',
            field=models.CharField(blank=True, db_column='numTel1_fr', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='opposant',
            name='numtel2',
            field=models.CharField(blank=True, db_column='numTel2_ar', max_length=20, null=True),
        ),
    ]
