# Generated by Django 5.1.2 on 2025-09-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prenomclient',
        ),
        migrations.AddField(
            model_name='client',
            name='prenomclient_ar',
            field=models.CharField(blank=True, db_column='prenomClient_ar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenomclient_fr',
            field=models.CharField(blank=True, db_column='prenomClient_fr', max_length=255, null=True),
        ),
    ]
