# Generated by Django 5.2.4 on 2025-07-24 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fonctionclient_opposant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='affairejudiciaire',
            name='idfonctionclient',
            field=models.ForeignKey(blank=True, db_column='idFonctionClient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.fonctionclient'),
        ),
        migrations.AddField(
            model_name='affairejudiciaire',
            name='idopposant',
            field=models.ForeignKey(blank=True, db_column='idOpposant', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.opposant'),
        ),

        migrations.AddField(
            model_name='client',
            name='adresse1',
            field=models.CharField(blank=True, db_column='adresse1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse2',
            field=models.CharField(blank=True, db_column='adresse2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=255, null=True),
        ),

        migrations.AddField(
            model_name='client',
            name='numtel1',
            field=models.CharField(blank=True, db_column='numTel1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numtel2',
            field=models.CharField(blank=True, db_column='numTel2', max_length=20, null=True),
        ),

    ]
