# Generated by Django 5.2.4 on 2025-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_company_fields_and_type_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='adresse_ar',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='adresse_ar', null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='adresse_fr',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='adresse_fr', null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='barreau',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='barreau', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='prenom_ar',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='prenom_ar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='prenom_fr',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='prenom_fr', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='telephone',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='telephone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='ville_ar',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ville_ar', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='ville_fr',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ville_fr', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='idavocat',
            field=models.AutoField(db_column='idAvocat', max_length=50, primary_key=True, serialize=False),
        ),
    ]
