# Generated by Django 5.2.4 on 2025-07-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_affairejudiciaire_idclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='client',
            name='prenomclient',
            field=models.CharField(blank=True, db_column='prenomClient', max_length=255, null=True),
        ),

    ]
