# Generated by Django 5.2.4 on 2025-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_avocat_adresse_ar_avocat_adresse_fr_avocat_barreau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reference_client',
            field=models.CharField(blank=True, db_column='reference_client', error_messages={'unique': 'Cette référence client existe déjà.'}, max_length=50, null=True, unique=True),
        ),
    ]
