# Generated by Django 5.2.4 on 2025-07-24 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_affairejudiciaire_idclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='affairejudiciaire',
            name='roleclient',
            field=models.CharField(blank=True, choices=[('demandeur', 'Demandeur'), ('opposant', 'Opposant')], db_column='roleClient', max_length=20, null=True),
        ),

    ]
