# Generated by Django 5.2.4 on 2025-07-25 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_affairejudiciaire_roleclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='affairejudiciaire',
            name='annee_dossier',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='affairejudiciaire',
            name='code_dossier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),

        migrations.AddField(
            model_name='affairejudiciaire',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),

    ]
