# Generated by Django 5.2.4 on 2025-07-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_client_adresseclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AlterField(
            model_name='affairejudiciaire',
            name='idaffaire',
            field=models.AutoField(db_column='idAffaire', primary_key=True, serialize=False),
        ),
    ]
