# Generated by Django 5.2.4 on 2025-07-25 13:22

import django.db.models.deletion
from django.conf import settings


from django.db import migrations, models, connection

def drop_fk_constraint(apps, schema_editor):

    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE statut_affaire DROP FOREIGN KEY statut_affaire_ibfk_1;")

def add_fk_constraint(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE statut_affaire
            ADD CONSTRAINT statut_affaire_ibfk_1
            FOREIGN KEY (idAffaire) REFERENCES affairejudiciaire(idAffaire);
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_client_adresseclient_and_more'),

    ]

    operations = [
        migrations.RunPython(drop_fk_constraint),
        migrations.AlterField(
            model_name='affairejudiciaire',
            name='idaffaire',
            field=models.AutoField(primary_key=True, db_column='idAffaire'),
        ),
        migrations.AlterField(
            model_name='statutaffaire',
            name='idaffaire',
            field=models.ForeignKey(to='api.Affairejudiciaire', db_column='idAffaire', on_delete=models.DO_NOTHING),
        ),
        migrations.RunPython(add_fk_constraint),
    ]