# Generated by Django 5.2.4 on 2025-07-25 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_client_adresseclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tribunal',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='tribunal',
            name='parent',
            field=models.ForeignKey(
                to='api.tribunal',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                db_column='idTribunalParent',
            ),
        ),
    ]
