# Generated by Django 5.2.4 on 2025-07-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tribunal_options_remove_client_adresseclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': "Catégorie d'affaire",
                'verbose_name_plural': "Catégories d'affaires",
                'db_table': 'categorie_affaire',
            },
        ),
        migrations.CreateModel(
            name='SousTypeAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': "Sous-type d'affaire",
                'verbose_name_plural': "Sous-types d'affaires",
                'db_table': 'sous_type_affaire',
            },
        ),
        migrations.CreateModel(
            name='TypeAffairePrincipale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': "Type d'affaire principale",
                'verbose_name_plural': "Types d'affaires principales",
                'db_table': 'type_affaire_principale',
            },
        ),

        migrations.AddField(
            model_name='tribunal',
            name='categories_affaires',
            field=models.ManyToManyField(blank=True, related_name='tribunaux', to='api.categorieaffaire'),
        ),
        migrations.AddField(
            model_name='categorieaffaire',
            name='sous_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soustypeaffaire'),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='sous_types_affaires',
            field=models.ManyToManyField(blank=True, related_name='tribunaux', to='api.soustypeaffaire'),
        ),
        migrations.AddField(
            model_name='soustypeaffaire',
            name='type_principale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeaffaireprincipale'),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='types_affaires',
            field=models.ManyToManyField(blank=True, related_name='tribunaux', to='api.typeaffaireprincipale'),
        ),
    ]
