# Generated by Django 5.2.4 on 2025-07-26 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_categorieaffaire_soustypeaffaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairejudiciaire',
            name='idopposant',
        ),

        migrations.CreateModel(
            name='AffaireOpposantAvocat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(auto_now_add=True, help_text='Date de début de la défense')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de la défense (si applicable)', null=True)),
                ('role_avocat', models.CharField(blank=True, help_text="Rôle de l'avocat (ex: défenseur, conseil)", max_length=100, null=True)),
                ('actif', models.BooleanField(default=True, help_text="Si l'avocat défend actuellement cet opposant")),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposants_avocats', to='api.affairejudiciaire')),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaires_opposants', to='api.avocat')),
                ('opposant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaires_avocats', to='api.opposant')),
            ],
            options={
                'verbose_name': 'Relation Affaire-Opposant-Avocat',
                'verbose_name_plural': 'Relations Affaire-Opposant-Avocat',
                'db_table': 'affaire_opposant_avocat',
                'unique_together': {('affaire', 'opposant', 'avocat')},
            },
        ),
    ]
