# Generated by Django 5.2.4 on 2025-07-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_client_adresseclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tribunal',
            options={'managed': True, 'verbose_name': 'Tribunal', 'verbose_name_plural': 'Tribunaux'},
        ),
        migrations.AlterModelOptions(
            name='typetribunal',
            options={'managed': True, 'verbose_name': 'Type de tribunal', 'verbose_name_plural': 'Types de tribunaux'},
        ),
        migrations.AddField(
            model_name='typetribunal',
            name='code_type',
            field=models.CharField(
                max_length=10,
                unique=True,
                help_text="Code unique pour identifier le type",
                null=True,  # Temporaire pour permettre la migration
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='typetribunal',
            name='niveau',
            field=models.CharField(
                max_length=50,
                help_text="Niveau dans la hiérarchie judiciaire",
                null=True,  # Temporaire pour permettre la migration
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='typetribunal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),






    ]
