# Generated by Django 5.2.4 on 2025-07-28 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tribunal_options_alter_typetribunal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AlterField(
            model_name='contrat',
            name='idcontrat',
            field=models.AutoField(db_column='idContrat', primary_key=True, serialize=False),
        )
    ]
