# Generated by Django 5.2.4 on 2025-07-29 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_client_adresseclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandesFichier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_demande', models.CharField(choices=[('COPIE_JUGEMENT', 'Copie de jugement'), ('PIECE_PROCEDURE', 'Pièce de procédure'), ('EXPERTISE', "Rapport d'expertise"), ('AUDIENCE', "Compte-rendu d'audience"), ('AUTRE', 'Autre')], max_length=50)),
                ('description', models.TextField(help_text='Description détaillée de la demande')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField(blank=True, help_text='Date limite pour la réponse', null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('EN_COURS', 'En cours de traitement'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de fichier',
                'verbose_name_plural': 'Demandes de fichiers',
                'db_table': 'demande_fichier',
            },
        ),
        migrations.CreateModel(
            name='Juge',
            fields=[
                ('idjuge', models.AutoField(primary_key=True, serialize=False)),
                ('nomjuge', models.CharField(max_length=255)),
                ('prenomjuge', models.CharField(max_length=255)),
                ('matricule', models.CharField(help_text='Numéro matricule du juge', max_length=50, unique=True)),
                ('specialisation', models.CharField(blank=True, help_text='Spécialisation du juge', max_length=100, null=True)),
                ('actif', models.BooleanField(default=True, help_text='Si le juge est actuellement en fonction')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Juge',
                'verbose_name_plural': 'Juges',
                'db_table': 'juge',
            },
        ),



        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('fichier', models.FileField(help_text='Fichier uploadé', upload_to='fichiers_affaires/%Y/%m/%d/')),
                ('type_fichier', models.CharField(choices=[('JUGEMENT', 'Jugement'), ('PIECE_PROCEDURE', 'Pièce de procédure'), ('EXPERTISE', "Rapport d'expertise"), ('AUDIENCE', "Compte-rendu d'audience"), ('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('CORRESPONDANCE', 'Correspondance'), ('AUTRE', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', help_text='Version du fichier', max_length=10)),
                ('public', models.BooleanField(default=False, help_text='Si le fichier est accessible publiquement')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='api.affairejudiciaire')),
                ('demande_fichier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers', to='api.demandesfichier')),
                ('upload_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
                'db_table': 'fichier',
            },
        ),
        migrations.CreateModel(
            name='AffaireJuge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_juge', models.CharField(help_text='Rôle du juge (rapporteur, président, etc.)', max_length=100)),
                ('date_debut', models.DateField(auto_now_add=True, help_text="Date de début d'intervention")),
                ('date_fin', models.DateField(blank=True, help_text="Date de fin d'intervention", null=True)),
                ('actif', models.BooleanField(default=True, help_text='Si le juge intervient actuellement')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juges_affaire', to='api.affairejudiciaire')),
                ('juge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaires_juge', to='api.juge')),
            ],
            options={
                'verbose_name': 'Relation Affaire-Juge',
                'verbose_name_plural': 'Relations Affaire-Juge',
                'db_table': 'affaire_juge',
                'unique_together': {('affaire', 'juge', 'role_juge')},
            },
        ),
    ]
