# Generated by Django 5.2.4 on 2025-07-31 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_demandesfichier_juge_remove_client_adresseclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # nouvelles tables
        migrations.CreateModel(
            name='TypeAvertissement',
            fields=[
                ('idtypeavertissement', models.AutoField(db_column='idTypeAvertissement', primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='نوع الإنذار', max_length=100)),
                ('libelle_ar', models.CharField(help_text='نوع الإنذار بالعربية', max_length=100)),
                ('delai_legal', models.IntegerField(default=0, help_text='المدة القانونية')),
                ('obligatoire', models.BooleanField(default=True, help_text='إلزامي')),
                ('description', models.TextField(blank=True, help_text='وصف النوع', null=True)),
                ('categorie', models.CharField(choices=[('CIVIL', 'مدني'), ('COMMERCIAL', 'تجاري'), ('TRAVAIL', 'عمل'), ('FAMILLE', 'أسرة'), ('PENAL', 'جنائي')], default='CIVIL', help_text='فئة الإنذار', max_length=50)),
                ('notification_automatique', models.BooleanField(default=False, help_text='إشعار تلقائي')),
            ],
            options={
                'verbose_name': 'نوع الإنذار',
                'verbose_name_plural': 'أنواع الإنذارات',
                'db_table': 'type_avertissement',
            },
        ),
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('idtypedemande', models.AutoField(db_column='idTypeDemande', primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='نوع الطلب', max_length=100)),
                ('libelle_ar', models.CharField(help_text='نوع الطلب بالعربية', max_length=100)),
                ('categorie', models.CharField(choices=[('CIVIL', 'مدني'), ('COMMERCIAL', 'تجاري'), ('TRAVAIL', 'عمل'), ('FAMILLE', 'أسرة'), ('PENAL', 'جنائي'), ('ADMINISTRATIF', 'إداري')], default='CIVIL', help_text='فئة الطلب', max_length=50)),
                ('delai_legal', models.IntegerField(default=0, help_text='المدة القانونية')),
                ('actif', models.BooleanField(default=True, help_text='نشط')),
                ('description', models.TextField(blank=True, help_text='وصف النوع', null=True)),
                ('documents_requis', models.TextField(blank=True, help_text='المستندات المطلوبة', null=True)),
                ('notification_automatique', models.BooleanField(default=False, help_text='إشعار تلقائي')),
            ],
            options={
                'verbose_name': 'نوع الطلب',
                'verbose_name_plural': 'أنواع الطلبات',
                'db_table': 'type_demande',
            },
        ),

        # mod de affaire
        migrations.AlterModelOptions(
            name='affairejudiciaire',
            options={'managed': True, 'verbose_name': 'قضية قضائية', 'verbose_name_plural': 'القضايا القضائية'},
        ),
        migrations.AlterModelOptions(
            name='etapejudiciaire',
            options={'verbose_name': 'خطوة قضائية', 'verbose_name_plural': 'الخطوات القضائية'},
        ),

        migrations.AddField(
            model_name='affairejudiciaire',
            name='affaire_parent',
            field=models.ForeignKey(blank=True, db_column='idAffaireParent', help_text='القضية الأصلية في حالة الاستئناف', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.affairejudiciaire'),
        ),
        migrations.AddField(
            model_name='affairejudiciaire',
            name='date_debut_phase',
            field=models.DateField(blank=True, help_text='تاريخ بداية المرحلة الحالية', null=True),
        ),
        migrations.AddField(
            model_name='affairejudiciaire',
            name='delai_limite',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء الصلاحية للقضية', null=True),
        ),
        migrations.AddField(
            model_name='affairejudiciaire',
            name='etape_actuelle',
            field=models.ForeignKey(blank=True, db_column='idEtapeActuelle', help_text='الخطوة الحالية في العملية', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.etapejudiciaire'),
        ),


        migrations.AddField(
            model_name='affairejudiciaire',
            name='jours_retard',
            field=models.IntegerField(default=0, help_text='عدد أيام التأخير'),
        ),
        migrations.AddField(
            model_name='affairejudiciaire',
            name='observations_execution',
            field=models.TextField(blank=True, help_text='ملاحظات حول سير العملية', null=True),
        ),
        migrations.AddField(
            model_name='affairejudiciaire',
            name='phase_processus',
            field=models.CharField(choices=[('INITIALE', 'مرحلة أولية'), ('PROCEDURE', 'مرحلة إجرائية'), ('APPEL', 'مرحلة استئناف'), ('EXECUTION', 'مرحلة تنفيذ')], default='INITIALE', help_text='مرحلة العملية القضائية', max_length=20),
        ),


    #     pour etape jud



        migrations.AddField(
            model_name='etapejudiciaire',
            name='idtypeavertissement',
            field=models.ForeignKey(
                blank=True,
                db_column='idTypeAvertissement',
                help_text='نوع الإنذار',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='api.typeavertissement'
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='idtypedemande',
            field=models.ForeignKey(
                blank=True,
                db_column='idTypeDemande',
                help_text='نوع الطلب',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='api.typedemande'
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='delai_legal',
            field=models.IntegerField(
                default=0,
                help_text='المدة القانونية بالأيام'
            ),
        ),



        migrations.AddField(
            model_name='etapejudiciaire',
            name='date_debut_effective',
            field=models.DateField(
                blank=True,
                help_text='تاريخ بداية التنفيذ الفعلي',
                null=True
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='date_fin_effective',
            field=models.DateField(
                blank=True,
                help_text='تاريخ انتهاء التنفيذ الفعلي',
                null=True
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='ordre_etape',
            field=models.IntegerField(
                default=0,
                help_text='ترتيب الخطوة في العملية'
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='etape_obligatoire',
            field=models.BooleanField(
                default=True,
                help_text='خطوة إلزامية'
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='description_etape',
            field=models.TextField(
                blank=True,
                help_text='وصف تفصيلي للخطوة',
                null=True
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='documents_requis',
            field=models.TextField(
                blank=True,
                help_text='المستندات المطلوبة',
                null=True
            ),
        ),

        migrations.AddField(
            model_name='etapejudiciaire',
            name='observations_etape',
            field=models.TextField(
                blank=True,
                help_text='ملاحظات حول الخطوة',
                null=True
            ),
        ),




    ]
