# Generated by Django 5.2.4 on 2025-08-01 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_typeavertissement_typedemande_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [



        migrations.AddField(
            model_name='typeavertissement',
            name='actif',
            field=models.BooleanField(default=True, help_text='نشط'),
        ),

        migrations.CreateModel(
            name='ContactExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultat_contact', models.CharField(
                    choices=[
                        ('trouvé', 'Trouvé'),
                        ('non_trouvé', 'Non trouvé'),
                        ('abstention', 'Abstention')
                    ],
                    max_length=20
                )),
                ('date_contact', models.DateField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('idaffaire', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='contacts_execution',
                    to='api.affairejudiciaire'
                )),
            ],
            options={
                'verbose_name': "Contact d'exécution",
                'verbose_name_plural': "Contacts d'exécution",
                'db_table': 'contact_execution',
            },
        ),
        migrations.CreateModel(
            name='DemandeCoercition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvée', 'Approuvée'), ('rejetée', 'Rejetée'), ('en_cours', 'En cours')], default='en_attente', max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('idaffaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_coercition', to='api.affairejudiciaire')),
            ],
            options={
                'verbose_name': 'Demande de coercition',
                'verbose_name_plural': 'Demandes de coercition',
                'db_table': 'demande_coercition',
            },
        ),
        migrations.CreateModel(
            name='PV1Execution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_pv', models.CharField(
                    choices=[
                        ('abstention', 'Abstention'),
                        ('paiement', 'Paiement'),
                        ('ikhbaari', 'PV Ikhbaari')
                    ],
                    max_length=20
                )),
                ('montant_paye', models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    max_digits=10,
                    null=True
                )),
                ('date_pv', models.DateField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('idaffaire', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pv1_execution',
                    to='api.affairejudiciaire'
                )),
            ],
            options={
                'verbose_name': "PV 1 d'exécution",
                'verbose_name_plural': "PV 1 d'exécution",
                'db_table': 'pv1_execution',
            },
        ),
        migrations.CreateModel(
            name='PV_Informatif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_pv', models.DateField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('idaffaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_ikhbaari', to='api.affairejudiciaire')),
            ],
            options={
                'verbose_name': ' PV_Informatif',
                'verbose_name_plural': 'PV_Informatif ',
                'db_table': 'PV_Informatif',
            },
        ),


    ]
