# Generated by Django 5.2.4 on 2025-08-02 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_affairejudiciaire_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='affairejudiciaire',
            name='huissier_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_notification', to='api.huissier'),
        ),

        migrations.AddField(
            model_name='affairejudiciaire',
            name='opposant_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_notification', to='api.opposant'),
        ),



    ]
