# Generated by Django 5.2.4 on 2025-08-04 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_affairejudiciaire_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.RemoveField(
            model_name='pv1execution',
            name='idaffaire',
        ),
        migrations.RemoveField(
            model_name='pv_informatif',
            name='idaffaire',
        ),


        migrations.AlterField(
            model_name='affairejudiciaire',
            name='phase_processus',
            field=models.CharField(choices=[('INITIALE', 'Phase Initiale'), ('PROCEDURE', 'Phase Procédure'), ('APPEL', 'Phase Appel'), ('EXECUTION', 'Phase Exécution')], default='INITIALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandesfichier',
            name='type_demande',
            field=models.CharField(choices=[('COPIE_JUGEMENT', 'Copie de jugement'), ('PIECE_PROCEDURE', 'Pièce de procédure'), ('EXPERTISE', "Rapport d'expertise"), ('AUDIENCE', "Compte-rendu d'audience"), ('COERCITION', 'Demande de coercition'), ('AUTRE', 'Autre')], max_length=50),
        ),

        migrations.AlterField(
            model_name='fichier',
            name='type_fichier',
            field=models.CharField(choices=[('JUGEMENT', 'Jugement'), ('PIECE_PROCEDURE', 'Pièce de procédure'), ('EXPERTISE', "Rapport d'expertise"), ('AUDIENCE', "Compte-rendu d'audience"), ('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('CORRESPONDANCE', 'Correspondance'), ('PV_EXECUTION', "PV d'exécution"), ('PV_INFORMATIF', 'PV Informatif'), ('AUTRE', 'Autre')], max_length=50),
        ),




        migrations.CreateModel(
            name='PVExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_pv', models.CharField(choices=[('abstention', 'Abstention'), ('paiement', 'Paiement'), ('pv_informatif', 'PV Informatif')], max_length=20)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, help_text='المبلغ المدفوع', max_digits=10, null=True)),
                ('mode_paiement', models.CharField(blank=True, help_text='طريقة الدفع', max_length=50, null=True)),
                ('numero_recu', models.CharField(blank=True, help_text='رقم الإيصال', max_length=100, null=True)),
                ('motif_absence', models.TextField(blank=True, help_text='سبب عدم العثور على المدين', null=True)),
                ('date_pv', models.DateField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('demande_coercition', models.ForeignKey(blank=True, help_text='طلب الإكراه البدني', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.demandesfichier')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_execution', to='api.etapejudiciaire', to_field='idetape')),
            ],
            options={
                'verbose_name': "PV d'exécution",
                'verbose_name_plural': "PV d'exécution",
                'db_table': 'pv_execution',
            },
        ),
        migrations.DeleteModel(
            name='ContactExecution',
        ),

        migrations.DeleteModel(
            name='PV1Execution',
        ),
        migrations.DeleteModel(
            name='PV_Informatif',
        ),
    ]
