# Generated by Django 5.2.4 on 2025-08-11 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_demandecoercition_idaffaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='affairejudiciaire',
            name='avocat_demandeur_nom',
            field=models.CharField(blank=True, help_text="Nom de l'avocat du demandeur", max_length=255, null=True),
        ),

    ]
