# Generated by Django 5.2.4 on 2025-08-21 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_rdv_fields_to_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_language',
            field=models.CharField(
                max_length=5,
                choices=[('fr', 'Français'), ('ar', 'العربية')],
                default='fr',
                null=True,
                blank=True,
                help_text="Langue préférée de l'interface utilisateur",
            ),
        ),
    ]